title: Grav
description: Free and responsive theme for GRAV. Port of Twenty Fifteen template by Wordpress.org.
author:
  name: Team Grav
  email: 'joe@test.com'
metadata:
    description: 'TwentyFifteen is a free and responsive theme for **Grav**. Its a port of TwentyFifteen template by HTML5UP.'

# Disable or enable sharing icons
share:
  facebook: true 
  twitter: true 

# Show calendar in sidebar
calendar: true 

# Sidebar position
sidebar_position: left

# Main Menu
menu:
  - text: External link
    link: "#" 

social:
  - text: Twitter
    url: http://twitter.com/getgrav
  - text: Facebook
    url: http://facebook.com
  - text: Google
    url: http://plus.google.com
  - text: Github
    url: https://github.com/getgrav/grav